---
name: GCC
on:
  push:
    paths-ignore:
    - .github/workflows/**
    - Ubuntu/**
    - '!.github/workflows/GCC.yml'
    - '!Ubuntu/GCC'
  pull_request:
    paths-ignore:
    - .github/workflows/**
    - Ubuntu/**
    - '!.github/workflows/GCC.yml'
    - '!Ubuntu/GCC'
  workflow_dispatch:

jobs:
  gcc:
    runs-on: ubuntu-latest
    name: gcc-${{ matrix.version }}

    permissions:
      contents: read
      packages: write

    strategy:
      fail-fast: false
      matrix:
        version: [4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 🔑 Log in to ghcr.io
      uses: docker/login-action@v3.4.0
      if: ${{ github.event_name == 'workflow_dispatch' }}
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        logout: false

    - name: 📤 Extract metadata from ghcr.io
      uses: docker/metadata-action@v5.7.0
      if: ${{ github.event_name == 'workflow_dispatch' }}
      id: ghcr
      with:
        images: ghcr.io/${{ github.repository }}-ubuntu-gcc-${{ matrix.version }}-x86_64:latest

    - name: 🔑 Log in to the hub.docker
      if: ${{ github.event_name == 'workflow_dispatch' }}
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.HUB_DOCKER }}
        logout: false

    - name: ⚙️ Build and push image
      uses: docker/build-push-action@v6.17.0
      with:
        context: ./Ubuntu
        build-args: |
          compiler=gcc-${{ matrix.version }}
        push: ${{ github.event_name == 'workflow_dispatch' }}
        file: ./Ubuntu/GCC
        tags: |
          ${{ github.repository }}-ubuntu-gcc-${{ matrix.version }}-x86_64:latest
          ghcr.io/${{ github.repository }}-ubuntu-gcc-${{ matrix.version }}-x86_64:latest
        labels: ${{ steps.hub.outputs.labels }}
