name: Remove package versions
on:
  schedule:
    - cron:  '0 8 * * *'
  workflow_dispatch:

jobs:
  remove-package-versions-gcc:
    strategy:
      fail-fast: false
      matrix:
        version: [4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5, 6, 7, 8, 9, 10, 11, 12]
    runs-on: ubuntu-latest
    steps:
      - name: Remove package versions
        id: remove-package-versions
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: container
          names: '${{ github.repository }}-ubuntu-gcc-${{ matrix.version }}-x86_64'
          keep: 1
          
  remove-package-versions-clang:
    strategy:
      fail-fast: false
      matrix:
        version: [3.5, 3.6, 3.7, 3.8, 3.9, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
    runs-on: ubuntu-latest
    steps:
      - name: Remove package versions
        id: remove-package-versions
        uses: smartsquaregmbh/delete-old-packages@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          type: container
          names: '${{ github.repository }}-ubuntu-clang-${{ matrix.version }}-x86_64'
          keep: 1
